import faiss
import numpy as np
import json
from sentence_transformers import SentenceTransformer
from fastapi import FastAPI
from pydantic import BaseModel
import requests  # Для запитів до Ollama API

# Ініціалізація FastAPI
app = FastAPI()

# Завантаження необхідних компонентів
print("Loading model, FAISS index, and texts...")

# Завантаження SentenceTransformer моделі
model = SentenceTransformer("Data/processed/wiki/sentence_transformer_model")  # Ваша модель векторайзера
print("Model loaded.")

# Завантаження FAISS-індексу
index = faiss.read_index("Data/processed/wiki/vector_index.faiss")
print("FAISS index loaded.")

# Завантаження даних текстів
with open("Data/processed/wiki_processed_results.json", "r", encoding="utf-8") as file:
    texts = json.load(file)
print("Texts loaded.")

# Налаштування API Ollama
OLLAMA_API_URL = "http://127.0.0.1:11434/api/generate"  # Локальний ендпоінт Ollama API


# Допоміжна функція: Знаходження схожих текстів
def find_similar_texts(query: str, k: int = 5):
    # Генерація ембеддингу для запиту
    query_embedding = model.encode([query])

    # Пошук найближчих сусідів у FAISS
    distances, indices = index.search(query_embedding, k)

    # Формування результатів
    results = [{"text": texts[idx], "distance": float(distance)} for idx, distance in zip(indices[0], distances[0])]
    return results


# Допоміжна функція: Запит до Ollama
def query_ollama(model_name: str, prompt: str):
    # Структура даних для запиту
    data = {
        "model": model_name,  # Назва моделі в Ollama
        "prompt": prompt,
        "stream": False
    }

    # Запит до Ollama API
    response = requests.post(OLLAMA_API_URL, json=data)

    # Перевірка відповіді
    if response.status_code == 200:
        try:
            json_response = response.json()

            # Перевіряємо, чи є "message" і "content"
            if "message" in json_response and "content" in json_response["message"]:
                result_content = json_response["message"]["content"]

                # Якщо повертається порожній результат
                if not result_content.strip():
                    return "No response generated by the model. Check the prompt or context for relevancy."
                return result_content
            else:
                raise KeyError(f"'content' key not found in API response under 'message': {json_response}")
        except json.JSONDecodeError:
            raise Exception(f"Failed to decode JSON response from Ollama API: {response.text}")
    else:
        # Якщо статус відповіді не 200, видаємо інформативну помилку
        raise Exception(f"Ollama API error: {response.status_code}, {response.text}")



# FastAPI маршрут: Запит до агента
class QueryRequest(BaseModel):
    query: str
    num_results: int = 5  # Кількість результатів FAISS


@app.post("/agent")
def agent_endpoint(request: QueryRequest):
    # Крок 1: Пошук схожих текстів у FAISS
    similar_texts = find_similar_texts(request.query, request.num_results)

    # Перевіряємо, чи знайдено хоч один схожий текст
    if not similar_texts:
        return {
            "query": request.query,
            "response": "No relevant context found for your query. Try rephrasing or providing more context.",
            "context": []
        }

    # Крок 2: Формуємо контекст, обмежуючи кількість тексту
    context = "\n\n".join([
        f"Context {i + 1}: {result['text']['processed_text'][:500]}"  # Обрізання, щоб уникнути надлишку
        for i, result in enumerate(similar_texts)
    ])

    # Крок 3: Формування інструкції для Ollama
    prompt = f"Використовуй контекст щоб відповісти на запит:\n\n{context}\n\nЗапит: {request.query}\nВідповідь:"

    # Крок 4: Звернення до Ollama через API
    response = query_ollama("phi4", prompt)

    # Крок 5: Формування результату для користувача
    return {
        "query": request.query,
        "response": response,
        "context": similar_texts
    }